# Generated by Django 2.1 on 2019-02-06 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rebu', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='eater',
        ),
        migrations.DeleteModel(
            name='eater_rating',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='cook_id',
        ),
        migrations.RemoveField(
            model_name='plate',
            name='meal_id',
        ),
        migrations.DeleteModel(
            name='review',
        ),
        migrations.DeleteModel(
            name='cook',
        ),
        migrations.DeleteModel(
            name='meal',
        ),
        migrations.DeleteModel(
            name='plate',
        ),
    ]
