# Generated by Django 2.1 on 2019-02-06 02:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rebu', '0002_auto_20190206_0217'),
    ]

    operations = [
        migrations.CreateModel(
            name='cook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signature_dish', models.TextField()),
                ('user_id', models.OneToOneField(default=-1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='rebu.user')),
            ],
        ),
        migrations.CreateModel(
            name='eater',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.OneToOneField(default=-1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='rebu.user')),
            ],
        ),
        migrations.CreateModel(
            name='eater_rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('description', models.TextField()),
                ('cook_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rebu.cook')),
                ('eater_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rebu.eater')),
            ],
        ),
        migrations.CreateModel(
            name='meal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calories', models.IntegerField()),
                ('description', models.TextField()),
                ('spice', models.IntegerField()),
                ('price', models.FloatField()),
                ('tags', models.TextField()),
                ('takeout_available', models.BooleanField()),
                ('num_plates', models.IntegerField()),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('cook_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rebu.cook')),
            ],
        ),
        migrations.CreateModel(
            name='plate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eater_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rebu.eater')),
                ('meal_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rebu.meal')),
            ],
        ),
        migrations.CreateModel(
            name='review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('description', models.TextField()),
                ('cook_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rebu.cook')),
                ('eater_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rebu.eater')),
                ('meal_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rebu.meal')),
            ],
        ),
    ]
