# Generated by Django 2.1 on 2019-02-07 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rebu', '0003_cook_eater_eater_rating_meal_plate_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cook',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='eater',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='eater_rating',
            old_name='cook_id',
            new_name='cook',
        ),
        migrations.RenameField(
            model_name='eater_rating',
            old_name='eater_id',
            new_name='eater',
        ),
        migrations.RenameField(
            model_name='meal',
            old_name='cook_id',
            new_name='cook',
        ),
        migrations.RenameField(
            model_name='plate',
            old_name='eater_id',
            new_name='eater',
        ),
        migrations.RenameField(
            model_name='plate',
            old_name='meal_id',
            new_name='meal',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='cook_id',
            new_name='cook',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='eater_id',
            new_name='eater',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='meal_id',
            new_name='meal',
        ),
    ]
