# Generated by Django 2.1 on 2019-02-21 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rebu', '0004_auto_20190207_0410'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='name',
            field=models.CharField(default='temp', max_length=30),
            preserve_default=False,
        ),
    ]
