# Generated by Django 2.1 on 2019-03-08 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rebu', '0006_auto_20190308_0714'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='username', max_length=30),
            preserve_default=False,
        ),
    ]
