# Generated by Django 2.1 on 2019-05-08 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rebu', '0011_auto_20190402_0224'),
    ]

    operations = [
        migrations.CreateModel(
            name='recommendations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommended_meals', models.CharField(max_length=100)),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rebu.meal')),
            ],
        ),
    ]
