language: python
services:
- docker
env:
- DOCKER_COMPOSE_VERSION=1.22.0
before_install:
- sudo rm /usr/local/bin/docker-compose
- curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname
  -s`-`uname -m` > docker-compose
- chmod +x docker-compose
- sudo mv docker-compose /usr/local/bin
install:
- docker pull mysql
- mkdir ~/build/rashidlasker/rebu/db
before_script:
- docker-compose up -f docker-compose.mysql.yml
- sleep 30
- docker ps -a
script:
- curl localhost:8000/ -f
- docker exec -it models bash -c "python manage.py test"
- docker exec -it selenium-test bash -c "pip install selenium; python selenium-webdriver.py"
after_script:
- docker-compose down --volumes
