language: python

services:
  - docker

install:
  # Setup mysql container
  - docker pull mysql:5.7.23
  - mkdir ~/build/rashidlasker/rebu/db
  - docker network create db_network
  - docker run --network=db_network --network-alias db --name mysql -d -e MYSQL_ROOT_PASSWORD='$3cureUS' -v ~/build/rashidlasker/rebu/db:/var/lib/mysql mysql:5.7.23
  - sleep 10
  - docker run --network=db_network -it --name mysql-cmdline --link mysql:db mysql:5.7.23 mysql -uroot -p'$3cureUS' -h db -e "CREATE USER 'www'@'%' IDENTIFIED BY '\$3cureUS'; CREATE DATABASE cs4501 CHARACTER SET utf8; GRANT ALL PRIVILEGES ON *.* TO 'www'@'%';"

before_script:
  # Startup the app
  - docker-compose up -d
  - sleep 30
  - docker ps -a

script:
  # Connection testing
  - curl localhost:8000/ -f
  # Unit testing
  - docker exec -it models bash -c "python manage.py test"
  # Integration testing
  - docker exec -it selenium-test bash -c "pip install selenium; python selenium-webdriver.py"

after_script:
  - docker-compose down
