models:
  image: tp33/django
  container_name: models
  links:
    - es:es
  external_links:
    - mysql:db
  volumes:
    - ./app/microservices:/app
  ports:
    - "8004:8000"
  command: bash start-microservices.sh

exp:
  image: tp33/django
  container_name: exp
  links:
    - models:models-api
    - kafka:kafka
    - es:es
  volumes:
    - ./app/exp:/app
  ports:
    - "8003:8000"
  command: bash start-exp.sh

web:
  image: tp33/django
  container_name: web
  links:
    - exp:exp-api
  volumes:
    - ./app/web:/app
  ports:
    - "8001:8000"
  command: bash start-web.sh

webb:
  image: tp33/django
  container_name: webb
  links:
    - exp:exp-api
  volumes:
    - ./app/web:/app
  ports:
    - "8002:8000"
  command: bash start-web.sh

kafka:
   image: spotify/kafka
   container_name: kafka
   environment:
      ADVERTISED_HOST: kafka
      ADVERTISED_PORT: 9092
   hostname: kafka

es:
   image: elasticsearch:2.0
   container_name: es
   ports:
      - "9200:9200"

batch:
   image: tp33/django
   container_name: batch
   volumes:
     - ./app/batch:/app
     - ./data:/tmp/data
   ports:
     - 8005:8000
   links:
      - kafka:kafka
      - es:es
   command: bash start-batch.sh

balancer:
   build: ./app/balancer
   container_name: balancer
   ports:
      -  "8000:8000"
      -  "1936:1936"
   links:
      -  web:web
      -  webb:webb
      -  exp:exp
      -  models:models

spark-master:
  image: gettyimages/spark
  command: bin/spark-class org.apache.spark.deploy.master.Master -h spark-master
  container_name: spark-master
  hostname: spark-master
  environment:
    MASTER: spark://spark-master:7077
    SPARK_CONF_DIR: /conf
  expose:
    - 7001
    - 7002
    - 7003
    - 7004
    - 7005
    - 7006
    - 7077
    - 6066
  ports:
    - 4040:4040
    - 6066:6066
    - 7077:7077
    - 8080:8080
  volumes:
    - ./app/spark:/tmp/spark
    - ./data:/tmp/data
  links:
    -  models:models

spark-worker:
  image: gettyimages/spark
  command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
  container_name: spark-worker
  hostname: spark-worker
  environment:
    SPARK_CONF_DIR: /conf
    SPARK_WORKER_CORES: 2
    SPARK_WORKER_MEMORY: 512m
    SPARK_WORKER_PORT: 8881
    SPARK_WORKER_WEBUI_PORT: 8081
  links:
    - spark-master
  expose:
    - 7012
    - 7013
    - 7014
    - 7015
    - 7016
    - 8881
  ports:
    - 8081:8081
  volumes:
    - ./app/spark:/tmp/spark
    - ./data:/tmp/data

locust:
   image: christianbladescb/locustio
   container_name: locust
   volumes:
     - ./app/locust:/locust
   ports:
     - 8089:8089
   links:
      - balancer:balancer
   command: "--host http://balancer:8000"
