models:
  image: tp33/django
  container_name: models
  links:
    - es:es
  external_links:
    - mysql:db
  volumes:
    - ./app/microservices:/app
  ports:
    - "8004:8000"
  command: bash start-microservices.sh

exp:
  image: tp33/django
  container_name: exp
  links:
    - models:models-api
    - kafka:kafka
    - es:es
  volumes:
    - ./app/exp:/app
  ports:
    - "8003:8000"
  command: bash start-exp.sh

web:
  image: tp33/django
  container_name: web
  links:
    - exp:exp-api
  volumes:
    - ./app/web:/app
  ports:
    - "8001:8000"
  command: bash start-web.sh

webb:
  image: tp33/django
  container_name: webb
  links:
    - exp:exp-api
  volumes:
    - ./app/web:/app
  ports:
    - "8002:8000"
  command: bash start-web.sh

kafka:
   image: spotify/kafka
   container_name: kafka
   environment:
      ADVERTISED_HOST: kafka
      ADVERTISED_PORT: 9092
   hostname: kafka

es:
   image: elasticsearch:2.0
   container_name: es
   ports:
      - "9200:9200"

batch:
   image: tp33/django
   container_name: batch
   volumes:
     - ./app/batch:/app
   ports:
     - 8005:8000
   links:
      - kafka:kafka
      - es:es
   command: bash start-batch.sh

balancer:
   build: ./app/balancer
   container_name: balancer
   ports:
      -  "8000:8000"
      -  "1936:1936"
   links:
      -  web:web
      -  webb:webb
      -  exp:exp
      -  models:models
