models:
  image: tp33/django
  external_links:
    - mysql:db
  volumes:
    - ./app:/app
  ports:
    - "8000:8000"
  command: bash -c "python /app/marketplace/manage.py migrate && mod_wsgi-express start-server --working-directory /app/marketplace --reload-on-changes /app/marketplace/marketplace/wsgi.py"