models:
  image: tp33/django
  external_links:
    - mysql:db
  volumes:
    - ./app:/app
  ports:
    - "8000:8000"
  command: bash -c "python /app/microservices/manage.py migrate && mod_wsgi-express start-server --working-directory /app/microservices --reload-on-changes /app/microservices/microservices/wsgi.py"
