#!/bin/bash

for i in "$@"
do
case $i in
  start)
  echo "starting application"
  docker start mysql
  docker-compose build
  docker-compose up &
  ./start_spark.sh
  ;;
  restart)
  echo "restarting application"
  docker-compose down
  docker-compose build
  docker-compose up &
  ./start_spark.sh
  ;;
  stop)
  echo "stopping application"
  docker-compose down
  docker stop mysql
  ;;
  start-prod)
  echo "starting application"
  docker start mysql
  docker-compose -f docker-compose.prod.yml build
  docker-compose -f docker-compose.prod.yml up &
  ./start_spark.sh
  ;;
  restart-prod)
  echo "restarting application"
  docker-compose -f docker-compose.prod.yml down
  docker-compose -f docker-compose.prod.yml build
  docker-compose -f docker-compose.prod.yml up &
  ./start_spark.sh
  ;;
  stop)
  echo "stopping application"
  docker-compose -f docker-compose.prod.yml down
  docker stop mysql
  ;;
  mysql)
  docker run -it --name mysql-cmdline --link mysql:db mysql:5.7.23 mysql -uroot -p'$3cureUS' -h db -e "CREATE USER 'www'@'%' IDENTIFIED BY '\$3cureUS'; CREATE DATABASE cs4501 CHARACTER SET utf8; GRANT ALL PRIVILEGES ON *.* TO 'www'@'%';"
  ;;
  help)
  echo "valid commands are start, restart, and stop for development and start-prod, restart-prod, and stop-prod for production, as well as mysql to set up the database"
  ;;
  *)
  echo "That is not an option, try ./script.sh help for help"
  ;;
esac
done

